### PR TITLE
Fix upgrade-facets script

### LINKED ISSUE #515: Fix upgrade-facets script
fix the upgrade-facets script that it will call `setAllowlistedFunctions` during the upgrade. It just needs to handle those selectors that were added or removed. No need to do anything about the replaced ones.

### PR DESCRIPTION
**Pull request by 0xlucian**
close #515

### CODE REVIEW

File: scripts/upgrade/generate-upgrade-config.ts [hunk 1]
```diff
@@ -140,6 +156,20 @@ async function generateUpgradeConfig(
       }
     }
 
+    const metaTxAllowlistAdd = newContracts
+      .filter((contract) => contract.endsWith("Facet") && !contract.includes("/test/") && !contract.includes("Mock"))
+      .flatMap((contractName) => {
+        const details = targetBytecodes[contractName]?.functionSignatures || [];
+        return details.map((detail) => ({ facetName: contractName, functionName: detail.name, hash: detail.hash }));
+      });
+
```
Comment (zajck) [inline scripts/upgrade/generate-upgrade-config.ts:165]: You also need to take into account the changes in `changedContracts`, i.e. find the selectors that existed in old facets, but not anymore, and find the selectors that were introduced in the target version.

**Review by zajck — CHANGES_REQUESTED** [review]

File: scripts/upgrade/generate-upgrade-config.ts [hunk 2]
```diff
@@ -4,10 +4,31 @@ import fs from "fs";
...
 
 const prefix = "contracts/";
 const sources = ["diamond", "protocol/facets", "protocol/clients", "protocol/bases", "protocol/libs"];
 
+const RESTRICTED_FUNCTIONS = [
+  "burn",
+  "mint",
+  "renounceOwnership",
+  "transferOwnership",
+  "setTransferValidator",
```
Comment (zajck) [inline scripts/upgrade/generate-upgrade-config.ts:17]: `setTransferValidator` does not need to be restricted.

File: scripts/upgrade/generate-upgrade-config.ts [hunk 3]
```diff
@@ -4,10 +4,31 @@ import fs from "fs";
...
+  "transferFractionsFrom",
+  "addPriceOracle",
+  "removePriceOracle",
+  "adjustVotesOnTransfer",
+  "migrateFractions",
```
Comment (zajck) [inline scripts/upgrade/generate-upgrade-config.ts:22]: `migrateFractions` does not need to be restricted.

File: scripts/upgrade/upgrade-facets.ts [hunk 4]
```diff
@@ -570,4 +638,17 @@ async function executeFacetUpdates(
   } else {
     console.log("ℹ️  No facet cuts to execute");
   }
+
+  // Update MetaTransactionFacet allowlist
+  if (config.metaTxAllowlist) {
+    const metaTransactionFacet = await hre.ethers.getContractAt("MetaTransactionFacet", protocolAddress);
+
+    if (config.metaTxAllowlist.add && config.metaTxAllowlist.add.length > 0) {
```
Comment (zajck) [inline scripts/upgrade/upgrade-facets.ts:646]: I think we should first do `remove` and then `add` case. 

For example, we have `contract A` with function `foo()`. But then A becomes too big and we split it into two contracts `contract A` and `contract B` and function `foo()` gets moved to `contract B`.  

Since it was removed from A and added to B, it will be on both `add` and `remove` lists. But if the remove is done 2nd, in the end state `foo()` won't be allowlisted even though it should be.

Alternatively, you can do one last bit of preprocessing, and remove all duplicates from `config.metaTxAllowlist.add` and `config.metaTxAllowlist.remove.length` and then the orderd does not matter.

File: scripts/upgrade/generate-upgrade-config.ts [hunk 5]
```diff
@@ -4,10 +4,31 @@ import fs from "fs";
...
+  "setMaxRoyaltyPercentage",
+  "setOpenSeaFeePercentage",
+  "setProtocolFeeTable",
```
Comment (zajck) [inline scripts/upgrade/generate-upgrade-config.ts:25]: I suppose we should add all functions from `configFacet` here, not only the new ones. Probably you could just exclude the whole `configFacet` and similarly the `pauseFacet`.

**Review by zajck — CHANGES_REQUESTED** [review]
Two things in addition to inline comments:

1. `upgrade-facets` is returning wrong `💰 Gas spent`.
2. In `deploy` we are still allowlisting to many functions in  
https://github.com/fermionprotocol/contracts/blob/c332d7a9eee7ec78a1641122325f2075e6f6d49f/scripts/deploy.ts#L243-L246
Can you update that too so it takes into account `RESTRICTED_FUNCTIONS`.

**Comment by zajck** [comment]
> > Two things in addition to inline comments:
> > 
> > 1. `upgrade-facets` is returning wrong `💰 Gas spent`.
> > 2. In `deploy` we are still allowlisting to many functions in
> >    https://github.com/fermionprotocol/contracts/blob/c332d7a9eee7ec78a1641122325f2075e6f6d49f/scripts/deploy.ts#L243-L246
> >    
> >    Can you update that too so it takes into account `RESTRICTED_FUNCTIONS`.
> 
> about 2. in `deploy` script is it sufficient just to add into account `RESTRICTED_FUNCTIONS`? Don't we also need to preprocess `facetNames` and exclude facets like `ConfigFacet` and `PauseFacet`

@0xlucian Yes, we should also remove `ConfigFacet` and `PauseFacet` from the list.

**Review by zajck — APPROVED** [review]
LGTM :+1:
